version: '3'
services:
  db:
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vitewp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3606:3306"
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=vitewp
    volumes:
      - ./wordpress:/var/www/html
volumes:
  db_data: